# Generated by Django 3.2.8 on 2021-11-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211103_2115'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='block_for_yourself',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
    ]
