# Generated by Django 3.2.8 on 2021-10-25 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_delete_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Описание')),
                ('tag', models.SlugField(verbose_name='Тег')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления в минутах')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepts', to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#49B64E', max_length=7, verbose_name='Цветовой HEX-код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='Recept',
        ),
    ]
