# Generated by Django 3.2.8 on 2021-11-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20211103_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
    ]
