# Generated by Django 3.2.8 on 2021-11-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(upload_to='images/', verbose_name='Картинка'),
        ),
    ]
